### ISSUE TITLE
Communication Contact annotation not working on object page header

### ISSUE THREAD

**Issue by js1972** [SAP-samples/fiori-elements-incident-management#1]
The communication contact annotation shown below does not work in the object page header:
```
   FieldGroup #HeaderGeneralInformation : {
        $Type : 'UI.FieldGroupType',
        Data : [
            {
                Value : priority_code
            },
            {
                Value : incidentStatus_code
            },
            {
                Value : category_code
            },
            {
                $Type  : 'UI.DataFieldForAnnotation',
                Target : 'assignedIndividual/@Communication.Contact',
                Label  : '{i18n>AssignedContact}'
            }
        ]
    },
```

but if I add the same piece to a facet on the main page it works fine (still shows yellow squigglies in the editor though):
```
    FieldGroup #GeneralInformation : {
        $Type : 'UI.FieldGroupType',
        Data : [
            {
                $Type : 'UI.DataField',
                Value : priority_code,
            },
            {
                $Type : 'UI.DataField',
                Value : category_code,
            },
            {
                $Type : 'UI.DataField',
                Value : incidentStatus_code,
            },
            {
                $Type  : 'UI.DataFieldForAnnotation',
                Target : 'assignedIndividual/@Communication.Contact',
                Label  : '{i18n>AssignedContact}'
            }
        ],
    },
```

Any ideas?

**Comment by ARiesterer** [comment]
Hi Jason,
thanks for pointing this out.
Actually I have no explanation why the contact is not shown anymore on the OP header. My assumption is, that it´s a bug in the current UI5 environment available in the cloud platform. My local environment using the latest UI5 libraries do not show the issue. Also, this must have worked before since the screenshots taken for the tutorial do also show the contact correctly. I have uploaded a fix showing the contact within a separate ReferenceFacet of the HeaderFacet. Of course this is not the real solution for the issue. I would just wait for some time to check whether this issue will be gone within the next days due to an upload of a new UI5 version into the cloud environment.
Best regards
Andreas

**Comment by ARiesterer** [comment]
Should be fixed meanwhile, therefore closing the issue.
